title: Dylan Samuelian's Homepage
page-top-title: Dylan Samuelian
top-section-bg-text: Dr. en Mathématiques
home-subtitle: Dylan Samuelian
notes-page-title: Notes & PDFs
music-page-title: Musique & Danse
