title: Dylan Samuelian's Homepage
page-top-title: Dylan Samuelian
top-section-bg-text: Dr. en Mathématiques
home-subtitle: Dylan Samuelian
notes-page-title: Notes et documents PDF
music-page-title: Musique & Danse
music-section-title: MUSIQUE
dance-section-title: DANSE
student-projects-section-title: PROJETS ÉTUDIANTS
science-communication-section-title: COMMUNICATION SCIENTIFIQUE
