title: Dylan Samuelian's Homepage
page-top-title: Dylan Samuelian
top-section-bg-text: Ph.D. in Mathematics
home-subtitle: Dylan Samuelian
notes-page-title: Notes & PDFs
music-page-title: Music & Dance
music-section-title: MUSIC
dance-section-title: DANCE
student-projects-section-title: STUDENT PROJECTS
science-communication-section-title: SCIENTIFIC COMMUNICATION
